### PR TITLE
Add option "--no-bootloader": this option disable the installation of the EFI packages

### PR DESCRIPTION
**Pull request by crigoda**
Hi,

I added the option "--no-botloader" to the live-installer.
This option only disable the installation of the grub-efi-* packages. This is useful for users like me that ran into a system freeze when theose packages are installed by the installer.

### CODE REVIEW

**Comment by clefebvre** [comment]
Hi @crigoda, that option is there already in the UI. Why do you need it to be set via console?

**Comment by crigoda** [comment]
Hi clefebre,

Well, the origin of my problem is that the UI option only disable GRUB configuration "grub-install" ~line 627 in installer.py.
But this don't disable the installation of the bootloader packages ~ line 118 in installer.py. The installed packages are the following:
pool/main/g/grub2/grub-efi*
pool/main/g/grub-efi-amd64-signed/*
pool/main/s/shim*/*
and this is the grub-efi-amd64 package postinst that made my system freeze.

Searching for a solution, I found that Ubuntu/Mint has a --no-bootloader option but this was absent from LDME.
As this option disable completly the bootloader packages installation, not only grub configuration, I think this is a very expert option.

**Comment by clefebvre** [comment]
Shouldn't we just make the UI option disable both instead?

**Comment by crigoda** [comment]
It's another good solution.
Do you prefer this way ? If yes, I can make te change and test it.
Do you think the text of UI option should be updated ?

**Comment by mtwebster** [comment]
I don't think any label needs to be updated.  I more or less consider these things all the same concept, and disabling it should disable all of it.

**Pull request closed without merging**
