### PR TITLE
[Refactoring] Replaced commands.getoutput and subprocess.Popen with utils.* replacements

### PR DESCRIPTION
**Pull request by kernc**
Looking to be forward-compatible, commands module is not in Python 3 and it's good to have things a bit unified. Also allows for one central place to print debug messages of what is going on.

### CODE REVIEW

**Comment by kernc** [comment]
This has also been rebased, hopefully you can give it a look, and you approve.

**Comment by kernc** [comment]
@clefebvre You don't like the change?

**Comment by clefebvre** [comment]
Hi @kernc,

I do, it's just been sitting there since 2015, waiting to be tested and it's something I can do easily when we port it to python3. I thought it was time to either merge it or be done with it, and we're not ready to test so it's time to clean up.

**Comment by kernc** [comment]
But it's a clean effort towards Python 3 and there aren't any dense, structural changes involved. Why close it outright? I can work on it if there is something to be addressed.

**Pull request closed without merging**
