### PR TITLE
Use streamer for webcam face capture

### PR DESCRIPTION
**Pull request by kernc**
A simple small V4L-compatible utility. streamer, replaces OpenCV, the code for which, as used, was deprecated anyway.

### CODE REVIEW

**Comment by kernc** [comment]
Bump. :-)

The arguments for streamer as opposed to OpenCV are these:
  * streamer is a simple, small, and tested utility, uses V4L (what only matters),
  * python-opencv pulls-in OpenCV, several libopencv* packages, altogether a pretty large library,
  * OpenCV webcam photo acquisition code, as used, was deprecated years ago and should stop working in the nearest future.

If we're not doing auto face detection with biometric feature extraction, OpenCV is an overkill.

**Comment by clefebvre** [comment]
What webcam was this tested with?

**Comment by kernc** [comment]
Regular USB webcam. It should work with any webcam. As the former implementation, this too uses the first recognized Video4Linux device, e.g. /dev/video0.

**Comment by dralley** [comment]
Hi @kernc 

I was testing this code to include in a Pull Request for Cinnamon, and I noticed that ```convert``` doesn't do exactly what the old algorithm was doing.  Since it doesn't crop to a square first, it just scales down the image to less than 96x96, meaning you get a non-square account picture.

**Comment by kernc** [comment]
Thanks. Both fixed.

**Comment by kernc** [comment]
Well, this took long enough. Thanks for merging. :smiley:

**Pull request merged**
